name: CI

on:
  push:
    branches:
    - main
    - track/**
  pull_request:

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
    - uses: Gr1N/setup-poetry@15821dc8a61bc630db542ae4baf6a7c19a994844 # v8

    - run: sudo apt update
    - run: sudo apt install python3-pip python3-cachecontrol tox
    - run: tox -e lint

  unit:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
    - uses: Gr1N/setup-poetry@15821dc8a61bc630db542ae4baf6a7c19a994844 # v8

    - run: sudo apt update
    - run: sudo apt install python3-pip python3-cachecontrol tox
    - run: tox -e unit
